name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        emacs_version:
          - 28.1
          - 28.2
          - 29.1
          - 29.2
          - 29.3
          # origami.elでエラーが出るのでとりあえず無視する
          # - snapshot

    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/cache@v4
      id: cache-cask-packages
      with:
        path: .cask
        key: cache-cask-packages-000

    - uses: actions/checkout@v4

    - run: git clone https://github.com/cask/cask.git "$HOME/.cask"
    - run: echo "$HOME/.cask/bin" >> $GITHUB_PATH

    - run: cask
    - run: cp -r . ~/.emacs.d

    - name: Check startup
      run: ./test-startup.sh

    - name: Generate elisp
      run: make gen-el

    - name: Generate HTML
      run: make gen-html

    - name: check
      run: ls -al ./public

    - name: Publish generated content to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.6.3
      with:
        branch: gh-pages
        folder: public
